
path: /Users/mateuscardoso/Documents/ESTUDOS_Py/YOLO_AVIARIO/train-yolov8-custom-dataset-step-by-step-guide/Arq_TESTE_AVES_001/data # dataset root dir
train: /Users/mateuscardoso/Documents/ESTUDOS_Py/YOLO_AVIARIO/train-yolov8-custom-dataset-step-by-step-guide/Arq_TESTE_AVES_001/data/images/train  # train images (relative to 'path')
val: /Users/mateuscardoso/Documents/ESTUDOS_Py/YOLO_AVIARIO/train-yolov8-custom-dataset-step-by-step-guide/Arq_TESTE_AVES_001/data/images/validation
# Classes
names:
  0: comedouro
